#Example https://medium.com/@amalec/alexa-skills-with-go-54db0c21e758
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  foodielambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: deployment.zip
      Environment:
        Variables: 
          S3_BUCKET: msundt.foodie
